services:
  - type: web
    name: hospital-pdf-checker
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update -y
      apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run ocr.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
